#include "usb_bootstrap.h"
#ifdef ARDUINO
#include <string.h>
#include "sensor_config.h"
#include "silabs_additional.h"
#include "sl_bluetooth.h"

static void hardware_id(char* output,size_t capacity){uint64_t id=getDeviceUniqueId();snprintf(output,capacity,"0x%08lX%08lX",(unsigned long)(id>>32),(unsigned long)id);}
static bool secure_hex(char* output,size_t capacity){
  if(capacity<33)return false;uint8_t bytes[16];size_t length=0;
  if(sl_bt_system_get_random_data(sizeof(bytes),sizeof(bytes),&length,bytes)!=SL_STATUS_OK||length!=sizeof(bytes))return false;
  for(size_t i=0;i<sizeof(bytes);i++)snprintf(output+i*2,3,"%02X",bytes[i]);return true;
}

static bool json_string(const char* json,const char* field,char* out,size_t cap){
  char needle[48];snprintf(needle,sizeof(needle),"\"%s\":\"",field);const char* p=strstr(json,needle);if(!p)return false;p+=strlen(needle);size_t n=0;
  while(*p&&*p!='\"'){if(*p=='\\'||(uint8_t)*p<0x20||n+1>=cap)return false;out[n++]=*p++;}if(*p!='\"')return false;out[n]='\0';return true;
}
static bool json_uint(const char* json,const char* field,uint32_t* out){
  char needle[48];snprintf(needle,sizeof(needle),"\"%s\":",field);const char* p=strstr(json,needle);if(!p)return false;p+=strlen(needle);if(*p<'0'||*p>'9')return false;uint32_t v=0;while(*p>='0'&&*p<='9'){uint32_t d=*p++-'0';if(v>(0xFFFFFFFFu-d)/10)return false;v=v*10+d;}*out=v;return true;
}
static const char* identity_status(NodeIdentityStore& store,NodeIdentity* id){StoreStatus s=store.load(id);return store_status_name(s);}
void UsbBootstrapProtocol::respond(Stream& s,const char* id,const char* action,const char* status,const char* result,const char* error){
  s.print(kBootstrapPrefix);s.print("{\"type\":\"bootstrap_response\",\"schema_version\":1,\"request_id\":\"");s.print(id);s.print("\",\"action\":\"");s.print(action);s.print("\",\"status\":\"");s.print(status);s.print("\"");
  if(error){s.print(",\"error_code\":\"");s.print(error);s.print("\"");}if(result){s.print(",\"result\":");s.print(result);}s.println("}");
}
void UsbBootstrapProtocol::poll(Stream& s,uint32_t now){while(s.available()){char c=(char)s.read();if(c=='\r')continue;if(c=='\n'){if(!overflow_&&length_){line_[length_]='\0';handle_line(line_,s,now);}else if(overflow_)respond(s,"unknown","unknown","error",nullptr,"line_too_large");length_=0;overflow_=false;}else if(length_<kBootstrapMaxLine)line_[length_++]=c;else overflow_=true;}}
bool UsbBootstrapProtocol::handle_line(const char* line,Stream& serial,uint32_t now){
  if(strncmp(line,kBootstrapPrefix,strlen(kBootstrapPrefix))!=0)return false;const char* json=line+strlen(kBootstrapPrefix);char request[kBootstrapMaxRequestId+1],type[24],action[40];uint32_t version=0;
  if(!json_string(json,"request_id",request,sizeof(request))||!json_string(json,"type",type,sizeof(type))||!json_string(json,"action",action,sizeof(action))||!json_uint(json,"schema_version",&version)){respond(serial,"unknown","unknown","error",nullptr,"malformed_request");return true;}
  if(strcmp(type,"bootstrap_request")||version!=1){respond(serial,request,action,"error",nullptr,"unsupported_schema_version");return true;}
  NodeIdentity id={};StoredChannelConfiguration cfg={};char result[700],hardware[19];hardware_id(hardware,sizeof(hardware));
  if(!strcmp(action,"read_node_state")||!strcmp(action,"backup_state")||!strcmp(action,"verify_state")){
    StoreStatus is=identities_.load(&id),cs=configurations_.load(&cfg);snprintf(result,sizeof(result),"{\"hardware_id\":\"%s\",\"provisioning_state\":\"%s\",\"node_id\":%s%s%s,\"identity_status\":\"%s\",\"identity_generation\":%lu,\"configuration_status\":\"%s\",\"configuration_generation\":%lu,\"sensor_package_version\":\"%s\",\"firmware_version\":\"%s\",\"protocol_version\":\"%s\",\"configuration_schema_version\":%d,\"build_identifier\":\"%s\",\"configuration\":{\"sample_interval_ms\":%lu,\"processing_interval_ms\":%lu,\"report_interval_ms\":%lu,\"heartbeat_interval_ms\":%lu,\"filter_type\":%u,\"filter_window\":%u,\"enabled\":%u,\"calibration_enabled\":false,\"alarms_enabled\":false,\"unit\":\"adc_count\"}}",
      hardware,(is==StoreStatus::Ok||is==StoreStatus::RecoveredFromPrevious)?"provisioned":"unprovisioned",(is==StoreStatus::Ok||is==StoreStatus::RecoveredFromPrevious)?"\"":"null",(is==StoreStatus::Ok||is==StoreStatus::RecoveredFromPrevious)?id.node_id:"",(is==StoreStatus::Ok||is==StoreStatus::RecoveredFromPrevious)?"\"":"",store_status_name(is),(unsigned long)id.generation,store_status_name(cs),(unsigned long)cfg.generation,SENSOR_PACKAGE_VERSION,FIRMWARE_VERSION,PROTOCOL_VERSION,CONFIGURATION_SCHEMA_VERSION,BUILD_IDENTIFIER,(unsigned long)cfg.sample_interval_ms,(unsigned long)cfg.processing_interval_ms,(unsigned long)cfg.report_interval_ms,(unsigned long)cfg.heartbeat_interval_ms,cfg.filter_type,cfg.filter_window,cfg.enabled);respond(serial,request,action,"success",result);return true;
  }
  if(!strcmp(action,"read_identity")){StoreStatus st=identities_.load(&id);snprintf(result,sizeof(result),"{\"hardware_id\":\"%s\",\"identity_status\":\"%s\",\"node_id\":%s%s%s,\"generation\":%lu}",hardware,store_status_name(st),(st==StoreStatus::Ok||st==StoreStatus::RecoveredFromPrevious)?"\"":"null",(st==StoreStatus::Ok||st==StoreStatus::RecoveredFromPrevious)?id.node_id:"",(st==StoreStatus::Ok||st==StoreStatus::RecoveredFromPrevious)?"\"":"",(unsigned long)id.generation);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"provision_identity")){char node[kNodeIdMaxLength+1];if(reset_.busy()){respond(serial,request,action,"error",nullptr,"persistent_operation_busy");return true;}if(!json_string(json,"node_id",node,sizeof(node))){respond(serial,request,action,"error",nullptr,"invalid_node_id");return true;}StoreStatus st=identities_.provision(node,&id);if(st!=StoreStatus::Ok){respond(serial,request,action,"error",nullptr,st==StoreStatus::InvalidArgument?"identity_already_provisioned_or_invalid":store_status_name(st));return true;}snprintf(result,sizeof(result),"{\"node_id\":\"%s\",\"generation\":%lu,\"verified\":true}",id.node_id,(unsigned long)id.generation);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"read_configuration")){StoreStatus st=configurations_.load(&cfg);snprintf(result,sizeof(result),"{\"configuration_status\":\"%s\",\"generation\":%lu,\"sample_interval_ms\":%lu,\"processing_interval_ms\":%lu,\"report_interval_ms\":%lu,\"heartbeat_interval_ms\":%lu,\"filter_type\":%u,\"filter_window\":%u,\"enabled\":%u,\"calibration_enabled\":false,\"alarms_enabled\":false,\"unit\":\"adc_count\"}",store_status_name(st),(unsigned long)cfg.generation,(unsigned long)cfg.sample_interval_ms,(unsigned long)cfg.processing_interval_ms,(unsigned long)cfg.report_interval_ms,(unsigned long)cfg.heartbeat_interval_ms,cfg.filter_type,cfg.filter_window,cfg.enabled);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"restore_configuration")){uint32_t sample,process,report,heartbeat,filter,window,enabled;if(reset_.busy()){respond(serial,request,action,"error",nullptr,"persistent_operation_busy");return true;}if(!json_uint(json,"sample_interval_ms",&sample)||!json_uint(json,"processing_interval_ms",&process)||!json_uint(json,"report_interval_ms",&report)||!json_uint(json,"heartbeat_interval_ms",&heartbeat)||!json_uint(json,"filter_type",&filter)||!json_uint(json,"filter_window",&window)||!json_uint(json,"enabled",&enabled)){respond(serial,request,action,"error",nullptr,"invalid_configuration");return true;}StoredChannelConfiguration proposed={};proposed.sample_interval_ms=sample;proposed.processing_interval_ms=process;proposed.report_interval_ms=report;proposed.heartbeat_interval_ms=heartbeat;proposed.filter_type=filter;proposed.filter_window=window;proposed.enabled=enabled;StoreStatus st=configurations_.write(proposed,&cfg);if(st!=StoreStatus::Ok){respond(serial,request,action,"error",nullptr,store_status_name(st));return true;}snprintf(result,sizeof(result),"{\"generation\":%lu,\"verified\":true}",(unsigned long)cfg.generation);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"prepare_factory_reset")){char scope_name[32],expected[19],operation[33],challenge[33];uint32_t reset_version=0;if(!json_uint(json,"reset_protocol_version",&reset_version)||reset_version!=2||!json_string(json,"scope",scope_name,sizeof(scope_name))||!json_string(json,"expected_hardware_id",expected,sizeof(expected))||strcmp(scope_name,"application_factory")){reset_.cancel();respond(serial,request,action,"error",nullptr,"secure_reset_v2_required");return true;}if(strcmp(expected,hardware)){reset_.cancel();respond(serial,request,action,"error",nullptr,"hardware_identity_mismatch");return true;}if(!secure_hex(operation,sizeof(operation))||!secure_hex(challenge,sizeof(challenge))){respond(serial,request,action,"error",nullptr,"secure_random_unavailable");return true;}ResetChallenge ch;StoreStatus st=reset_.prepare(ResetScope::ApplicationFactory,hardware,expected,operation,challenge,now,60000,&ch);if(st!=StoreStatus::Ok){respond(serial,request,action,"error",nullptr,store_status_name(st));return true;}snprintf(result,sizeof(result),"{\"reset_protocol_version\":2,\"scope\":\"application_factory\",\"hardware_id\":\"%s\",\"operation_id\":\"%s\",\"challenge\":\"%s\",\"expires_in_ms\":60000,\"identity_preserved\":false,\"reboot_required_after_confirm\":true}",hardware,ch.operation_id,ch.challenge);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"confirm_factory_reset")){char scope_name[32],expected[19],operation[33],challenge[33];uint32_t reset_version=0;if(!json_uint(json,"reset_protocol_version",&reset_version)||reset_version!=2||!json_string(json,"scope",scope_name,sizeof(scope_name))||!json_string(json,"expected_hardware_id",expected,sizeof(expected))||!json_string(json,"operation_id",operation,sizeof(operation))||!json_string(json,"challenge",challenge,sizeof(challenge))||strcmp(scope_name,"application_factory")){reset_.cancel();respond(serial,request,action,"error",nullptr,"invalid_confirmation");return true;}ResetResult rr=reset_.confirm(ResetScope::ApplicationFactory,expected,operation,challenge,now);if(rr.status!=StoreStatus::Ok){respond(serial,request,action,"error",nullptr,store_status_name(rr.status));return true;}snprintf(result,sizeof(result),"{\"reset_protocol_version\":2,\"scope\":\"application_factory\",\"hardware_id\":\"%s\",\"operation_id\":\"%s\",\"stage\":\"keys_cleared\",\"deleted_count\":%u,\"verified\":true,\"reboot_required\":true}",hardware,operation,rr.deleted_count);respond(serial,request,action,"success",result);return true;}
  if(!strcmp(action,"cancel_factory_reset")){reset_.cancel();respond(serial,request,action,"success","{\"cancelled\":true}");return true;}
  respond(serial,request,action,"error",nullptr,"unknown_action");return true;
}
#endif
